#!/usr/bin/zsh

case $1 in

  "push")
    git add .
    if [[ -z $2 ]]; then
        git commit -m "#auto-commit: [$(date)]"
      else
        git commit -m "commit: $2"
    fi
    git push -f
  ;;

  "pull")
    git pull -f
  ;;

  "main")
    git checkout main -f
  ;;

  *)
     echo "Invalid input: $1"
  ;;
esac